import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        App app = new App();

        System.out.println("Counting directories since 2017!");
        final String pathGivenByUser = app.askUserForAPath();
        System.out.println(pathGivenByUser);
        if (app.checkIfPathExists(pathGivenByUser)) {
            System.out.println("yaaaay! It exists!");
        }
    }

    boolean checkIfPathExists(String path) {
        return Files.exists(Paths.get(path));
    }

    String askUserForAPath() {
        System.out.println("Give me a path please: ");
        Scanner in = new Scanner(System.in);
        return in.nextLine();
    }
}
