/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.askUserForAPath(), "depends on scanner though...");
    }

    @Test public void doesItExist() {
        App app = new App();
        assertEquals(app.checkIfPathExists("I wonder if such a path exists"), true, "I sure hope I don't have a directory called 'I wonder if...'");
    }
}
